language: python
cache: pip
python:
  - '3.7'
install:
  - export PIPENV_VENV_IN_PROJECT=1
  - pip install pipenv
  - pipenv install
script:
  - flake8
  - python -m pytest
after_success:
  - pipenv run zappa update dev
